balderdashy/waterline

- lib/waterline/core/typecast.js
I am trying to implement [traceur](https://github.com/google/traceur-compiler) as a hook into sails 0.11 (see https://github.com/balderdashy/sails/issues/2517) and the only issue, apart from hook order is the `Object.keys(values).forEach` line when `values === null`. 
This if and return statement fixed it for me and traceur/ES6/7 code is now working in sails. Would love to see get this merged.
> Return undefined if values is undefined or null

- lib/waterline/query/composite.js
Whenever create fails in findOrCreate, the err variable is always null. I've added the missing `cb(err)`.
> Added missing err checking in create portion of findOrCreate()

- lib/waterline/utils/normalize.js
- package.json
On console there are:
```
npm WARN deprecated node-switchback@0.1.2: The 'node-switchback' NPM module is now simply 'switchback'.
```
And then I fixed that.
> The 'node-switchback' NPM module is now simply 'switchback'.

- lib/waterline/query/dql/destroy.js
I'm not sure if it covers all cases, but this fixes the issue about deleting related objects when removing a model with an invalid condition
> Fixes #812, moving destroy of related objects only if matching conditions

- lib/waterline/adapter/aggregateQueries.js
- lib/waterline/adapter/ddl/alter/index.js
- lib/waterline/query/composite.js
- test/unit/query/query.findOrCreate.js
When I had `Topic.findOrCreate({ researchId:  meta.id, text: meta.text }).exec()` as well as `Topic.findOrCreate([{ researchId:  meta.id, text: meta.text }, { researchId:  'bladi', text:  'kaaa' }]).exec()` in my app with https://github.com/balderdashy/sails-disk it just did not work properly.
Fixed that, added some more tests and changed `forEachSeries` to `eachSeries` since that seems to be the preferred name (now?) by the library https://github.com/caolan/async#eachseriesarr-iterator-callback
> fixed findOrCreate and added more tests.

- lib/waterline/query/validate.js
- lib/waterline/utils/callbacksRunner.js
For example, I want to set a "counter" on my model depending on a criteria.
```javascript
beforeValidate: function(values, cb) {
this.findOne({
where: criteria,
sort: { updatedAt: 'desc' }
}).exec(function(err, user) {
values.counter = user ? 0 : user.counter + 1;
cb();
});
```
Currently the context passed is the model prototype, why not the model ?
I could access to findOne but I got an error because _transformer is undefined.
> Bind model context to lifecycle callback

- lib/waterline/error/WLError.js
- test/unit/error/WLError.test.js
Fix for #865.  Makes waterline errors behave more like Error.  In particular, mocha tests which throw waterline errors will now report the error stack instead of just reporting nothing.
> Add stack and message properties to waterline errors

- example/express/express-example.js
Adds middleware dependencies that are no longer bundled with Express.
> Updated express example to use 'body-parser' and 'method-override'

- lib/waterline/adapter/sync/index.js
- lib/waterline/adapter/sync/strategies/create.js
- lib/waterline/query/index.js
This PR adds support for `create` migration strategy. It differs from `alter` by only running secure operations as `.define()` and `.addAttribute()` (if adapter implements it). More details in #846.
Tests added in balderdashy/waterline-adapter-tests#34
> #846: add migration strategy `create`

- README.md
According to http://stackoverflow.com/questions/27573734/how-do-i-use-findorcreateeach-in-waterline-sailsjs findOrCreateEach is deprecated.
Also I am not finding much about `findOneLike` or `findLike`. Are these deprecated as well?
> Deprecate findOrCreateEach

- lib/waterline/model/lib/associationMethods/update.js
- lib/waterline/model/lib/defaultMethods/save.js
- test/integration/model/save.js
Should fix critical bug #858.  After looking at more radical change in PR #861 to remove nested operation sync on update, @particlebanana suggested just targeting the issue from the model.  This passes all adapter tests that sails-memory currently passes using the waterline master branch and all vanilla waterline tests.
The approach is simply to remove attributes that are collections prior to passing the cloned model values to `ParentCollection.update`.
> Do not sync nested collections from Model#save.

- lib/waterline/adapter/aggregateQueries.js
This change aims to fix the the broken `.findOrCreateEach()` tests which are affecting most adapters.
Check balderdashy/waterline-adapter-tests#38 for more details.
> Fix .findOrCreateEach() test failures

- Makefile
- README.md
- package.json
Runs code coverage reports with `npm run coverage`.
@particlebanana, I highly suggest setting up waterline in https://codeclimate.com or similar. If you do so, let me know and I'll configure waterline to send code coverage reports to codeclimate on every build and add a badge with coverage to the README, such as this: [![Test Coverage](https://codeclimate.com/github/appscot/sails-orientdb/badges/coverage.svg)](https://codeclimate.com/github/appscot/sails-orientdb)
> Adds code coverage script

- Makefile
- package.json
In #896 we introduced adapter tests to be ran by waterline core test suite, but they have a minor flaw where waterline-adapter-tests is actually using waterline stable (0.10.x) instead of edge which is the aim of the tests.
This can easily be confirmed by checking the last master build log, where the "findOrCreateEach" test error ir still present even after being fixed: [previous build log #L1769](https://travis-ci.org/balderdashy/waterline/jobs/56325009#L1769).
The new build log shows (correctly) that error is now gone: [PR build log #L1768](https://travis-ci.org/balderdashy/waterline/jobs/56413696#L1768).
> Adapter Tests: waterline-adapter-tests using wrong WL dependency

- lib/waterline/utils/normalize.js
- test/unit/utils/utils.normalize.js
Issue #169.
Adds support for upper case `ASC` and `DESC` when sort criteria is passed as an object.
> #169: normalizes uppercase when sort passed as object

- lib/waterline/adapter/aggregateQueries.js
- test/unit/query/query.findOrCreate.js
This is as discussed in https://github.com/balderdashy/waterline-adapter-tests/issues/38
For some reason the unit-test I created did not catch the bug that broke my app. This now fully supports the use case I am using and that is described in https://github.com/balderdashy/waterline-docs/blob/master/query-methods.md#findorcreate-search-criteria-values-callback-, which is passing arrays of objects.
I tested now against https://github.com/balderdashy/waterline-adapter-tests and with `sails-memory` only get 1 failing test that is unrelated to my change.
@dmarcelino could you review?
> FindoOrCreate arrays of object fix

- lib/waterline/model/lib/model.js
- lib/waterline/query/finders/joins.js
Fix for #937: partially revert PR #924 to ensure `.save()` works on populated models.
Tests: balderdashy/waterline-adapter-tests#46.
> #937: saves on populated models

- test/adapter/runner.js
This is to avoid the case where the tests are broken but the build passes.
Part of issue #897.
> 897: if the adapter tests fail return code 1 so the automated build fails

- lib/waterline/utils/nestedOperations/update.js
Ref #533 and #930.
I think this is the correct fix for the problem referenced in issues above.  This should resolve the bugs caught in the adjusted adapter tests (https://github.com/balderdashy/waterline-adapter-tests/pull/44).
I'd call this fairly high priority for evaluating.  Happy to answer questions about the problem at hand and this solution.
> Use correct foreign collection during nested update creation/link step.

- lib/waterline/core/typecast.js
- test/unit/core/core.cast/cast.date.js
This means, for example, that I could pass in a Moment.js instance (or any of my own objects that implement toDate) straight into waterline and, with this PR, it would be cast appropriately.
Just a nice developer-friendly addition :smile:
> Allow objects that implement toDate to be cast

- lib/waterline/adapter/dql.js
Again, fixing a bug as discussed with @devinivy and @dmarcelino .
@devinivy I tried adding the shallow copy at the place you suggested first: https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/finders/basic.js#L35, but that did haven no affect in my code. Adding it here fixes the issue!
> Make shallow copy of criteria array for findOne

- lib/waterline/query/aggregate.js
createEach method: changing async.each to async.eachSeries. 
This allows to insert records in the same order as we expect. Also a lot of integraion tests from https://github.com/balderdashy/waterline-adapter-tests expect this behaviour.
> Update: query/aggregate.js

- lib/waterline/core/schema.js
- test/unit/core/core.schema/schema.cleanValues.js
Should resolve the ever-pesky #429 and https://github.com/balderdashy/sails-mongo/issues/254 .  This ensures that association attributes that represent collections are always cleaned by the schema before sending values to the adapter during create and update.  This should allow `schema: false` to behave correctly.  I added unit tests here– if anyone would like to add integration tests to [waterline-adapter-tests](https://github.com/balderdashy/waterline-adapter-tests), that would be sweet!
CC: @dmarcelino @tjwebb @anasyb
> Fix schema cleanValues method to always remove associations.

- lib/waterline/collection/defaults.js
- test/integration/Collection.ddl.js
Fixes #887.
Depends on balderdashy/waterline-adapter-tests#50 or the integration tests will be broken.
> #887: change default migration to 'safe'

- lib/waterline/query/finders/basic.js
- test/unit/query/associations/belongsTo.js
Fixes #860.
`findOne(undefined)` returns an error but `findOne(undefined).populate()` does not. This PR makes both uses of `.findOne()` consistent by always throwing error.
> 860: return error on findOne(undefined).populate()

- lib/waterline/core/validations.js
- test/unit/validations/validations.required.js
Fixes #867.
In the below case the e-mail validation does not run.
``` javascript
attributes: {
secondaryEmail: {
required: false,
email: true // this validation will not execute
}
}
```
The issue was traced to [validations.js#L138-L141](https://github.com/balderdashy/waterline/blob/master/lib/waterline/core/validations.js#L138-L141):
``` javascript
// if required is set to 'false', don't enforce as required rule
if (curValidation.hasOwnProperty('required')&&!curValidation.required) {
return cb();
}
```
This PR adds a failing test, 2 regressions tests and fixes this issue.
> 867: `required: false` prevents all other validators from running fix

- lib/waterline/query/aggregate.js
In #795, the `async.each` was replaced by `async.eachSeries` to ensure order of creation and make tests pass (for community adapters?), this however introduces a performance penalty which in my opinion and others is not worth:
@tjwebb in https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-68575680
> `.eachSeries` will slow things down, though, since each create will then be done sequentially. Should the order really matter, here?
@kevinburkeshyp in https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-95970705:
> would `async.map` help? 
@devinivy in https://github.com/balderdashy/waterline-adapter-tests/pull/27#issuecomment-96682857:
> I also would like to see `Async#map` being used as @dmarcelino mentioned.
Using …
> createEach: use async.map instead of async.eachSeries to improve performance

- lib/waterline/query/aggregate.js
instead of using helper array. to ensure the order is correct.
Supplement to #980, ensuring it passes the *.create() should return rows in the correct order when creating multiple rows* test.
cc: @devinivy, @kevinburkeshyp, @particlebanana, @brandonsimpson
> createEach: use the output of async.map

- README.md
In an effort to redirect users to ask questions in stackoverflow as opposed to raising new issues for questions.
Preview:
[![Build Status](https://travis-ci.org/balderdashy/waterline.svg?branch=master)](https://travis-ci.org/balderdashy/waterline) [![NPM version](https://badge.fury.io/js/waterline.svg)](http://badge.fury.io/js/waterline) [![Dependency Status](https://gemnasium.com/balderdashy/waterline.svg)](https://gemnasium.com/balderdashy/waterline) [![Test Coverage](https://codeclimate.com/github/balderdashy/waterline/badges/coverage.svg)](https://codeclimate.com/github/balderdashy/waterline) [![StackOverflow](http://img.shields.io/badge/stackoverflow-waterline-blue.svg)]( http://stackoverflow.com/questions/tagged/waterline)
Let me know what you guys think, namely about the badge's …
> Add stackoverflow badge

- lib/waterline/query/dql/update.js
- test/unit/query/query.update.nested.js
In `createBelongsTo()` of `lib/waterline/query/dql/update.js`, `valuesObject.associations.models` could be modified inside the iterator of `async.each()` function. This could lead to the final callback, which should be called only once, being called multiple times.
Here's an example of the effect of modifying an array being iterated by `async.each()`:
```js
var async = require('async');
var array = [1, 2, 3, 4, 5];
async.each(array, function(item, next) {
process.nextTick(function() {
console.log(item);
var index = array.indexOf(item);
array.splice(index, 1);
next();
});
}, function() { console.log('done'); });
```
will output:
```
1
2
3
done
4
done
5
done
```
> Fix callback being called multiple times when updating model with associations

- lib/waterline/query/finders/basic.js
- lib/waterline/query/finders/operations.js
- lib/waterline/query/integrator/index.js
Ok this should solve the issues that I currently know about in the integrator. 
RE: https://github.com/balderdashy/waterline/issues/925
* It fixes an issue when using column names on model associations where the transformer was getting the wrong data.
* It fixes an issue when using many-to-many associations across adapters where children weren't being populated.
* It fixes an issue where skip, sort, limit on collections that were on a different adapter weren't working correctly. (not a good idea because of memory issues but it works now)
I took @dmarcelino's awesome [PR for cross adapter joins](https://github.com/balderdashy/waterline-adapter-tests/pull/57) and expanded it a bit so I could run individual tests when debugging and they all passed for the adapters I ran it against. I'll …
> Integrator kungfu

- lib/waterline/query/finders/operations.js
Fix for https://github.com/balderdashy/waterline/issues/1014
Ensures that the join logic in operations gets set correctly on the connection registry.
I need to work on a major refactor of the operation builder so that it can be tested a lot better. Right now I'd be surprised if anyone besides me could figure out what the hell was going on! Now that I know how it works it can be refactored and tested. When I was building it there was a lot of ugghhhhh maybe this will work!
> M:M cross adapter issue #1014

- test/adapter/runner.js
To make use of the new cross-adapter tests introduced by balderdashy/waterline-adapter-tests#64.
This also increases coverage.
> Enable adapter/integration feature cross-adapter tests 

- lib/waterline/model/lib/associationMethods/add.js
- lib/waterline/query/dql/create.js
- lib/waterline/query/dql/update.js
- lib/waterline/utils/nestedOperations/create.js
- lib/waterline/utils/nestedOperations/reduceAssociations.js
- lib/waterline/utils/nestedOperations/update.js
This should fix #519 and #675. The issue was that when doing nested operations if the primaryKey was used then it assumed that the record already existed and would not try and create it. This was obviously a problem when you have non auto-incrementing primary keys where you need to specify the value.
Nested operations aren't my favorite thing but we should make what's there work. So what this does is check if the attribute is not auto-incrementing and that default autoPK flag is set to false and it's a create  or update method. If so it will let nested updates do it's thing. Otherwise it works as before and will just link the records together.
If someone else wouldn't mind giving this a quick test that would be great. @RWOverdijk would be great to test on mongo!
> Nested create/updates with a custom pk fix

- lib/waterline/model/lib/associationMethods/update.js
- test/integration/model/save.js
Fixes #1040 as per suggestion. Calling save no longer throws 'Cannot read property 'collections' of undefined'
> Fix for issue #1040.

- lib/waterline/error/WLError.js
- test/unit/error/WLError.test.js
Depends on PR #1061, so merge it afterwards!
Related to #1001 and #920, check https://github.com/shaunc/waterline/commit/cfbd38531b09b4411d8eb9a0e2fb1fc880e7917b#commitcomment-11710757.
cc: @devinivy
> Prevents infinite recursion in "WLError.message" setter

- lib/waterline/core/validations.js
- lib/waterline/query/validate.js
- test/unit/core/core.validations.js
The static `validate()` method on the model provides the `presentOnly` parameter to indicate that only the provided subset of values should be validated. When desiring to validate only a single modified value this can become problematic if that value depends on other attributes in the model, since the values of those attributes wouldn't be present at the time. Adding those values in is not ideal since it will cause them to be validated as well and requires extra code.
While this might not be a big issue on a server I am investigating the use of Waterline on the client in an isomorphic app. When some attributes require async validation to the server it becomes a big problem if I can't validate one property at a time, but then the issue in the first paragraph may come into play with the …
> validate() presentOnly parameter can be used to specify attributes to validate.

- lib/waterline/core/transformations.js
- lib/waterline/query/finders/basic.js
- test/unit/core/core.transformations/transformations.initialize.js
Added ability to transform columnName in populate() criteria.
Before this fix, `where` statement in populate() cannot use model attribute name.
Like this case.
```
// Article.js
module.exports = {
tableName: 'articles',
attributes: {
title: 'string',
body: 'string',
categories: {
collection: 'category',
through: 'articlecategory'
},
publicationDate : {
columnName: 'publication_date',
type: 'Date'
}
}
};
// Category.js
module.exports = {
tableName: 'categories',
attributes: {
name: 'string'
articles: {
collection: 'article',
through: 'articlecategory'
}
}
}
// ArticleCategory.js
module.exports = {
tableName: 'articles_categories',
tables: ['articles', 'categories'],
junctionTable: true,
attributes: {
article: {
columnName: 'article',
type: 'integer',
foreignKey: true,
references: …
```
> Added ability to transform columnName in populate() criteria

- lib/waterline/query/dql/count.js
- lib/waterline/query/dql/destroy.js
- lib/waterline/query/dql/update.js
- test/unit/query/query.destroy.js
Calling Collection.destroy({id: []}) destroys *all* documents. [Functionality exists in normalize that returns false if there's an empty array](https://github.com/balderdashy/waterline/blob/317cdf0173990face8afe67b336bc6e6d0fe5630/lib/waterline/utils/normalize.js#L191), but false is OR'd with {}, [resulting in a {} being passed to the sails-mongo adapter](https://github.com/balderdashy/sails-mongo/blob/master/lib/adapter.js#L367), which deletes everything.
This PR just applies [what is already implemented for find()](https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/finders/basic.js#L222).
We found this out the hard way. :(
> Return empty/zero from IN w/empty array

- lib/waterline/query/dql/create.js
- test/unit/query/query.create.js
If you are using `defaultsTo` and pass in a value of `undefined` the hasOwnProperty check was failing. This fixes that and will set the value correctly.
Also will need to be hot patched on the `0.10.x` branch after merge.
> Defaults to fix

- lib/waterline/query/aggregate.js
- lib/waterline/query/dql/create.js
- test/unit/query/query.create.js
This pullrequest goes along with the one I did for water-line schema [here](https://github.com/balderdashy/waterline-schema/pull/23) and implements #754 
It allows users to specify custom names for the automatic timestamp attributes, they just need to pass a string instead of `true` or `fals`e. 
Let me know if it is fine like this and I will update the documentation accordingly.
The Travis build will fail while [the PR on waterline-schema](https://github.com/balderdashy/waterline-schema/pull/23) is not merged, because my tests will not succeed, but all the older tests remain intact
Edit by @dmarcelino: Pending tasks:
> Use custom auto-attributes if specified in the model

- .travis.yml
- package.json
Possibly have a breaking change here.  Testing iojs has been removed, testing v4 and v5 has been added.  Added the specific tested engines into package.json to specify what waterline can actually claim to support.  Bottom line is good news: waterline passes all the tests on node v4 and node v5.  Also got the tests running on Travis's container infrastructure, which generates faster builds.  Closes #1203.
> Test node v4 and v5, support only tested node versions.

- lib/waterline/query/deferred.js
- test/unit/query/associations/populateArray.js
Its the usecase in between using populate as it is right now and populateAll. In this case, you can set in a single populate call all the collections and modules that need to be populated.
> Adds support for arrays on populate, like populate(['drivers','tickets'])

- README.md
FoundationDB doesn't exist as a separate company or a product anymore.
> Removed broken FoundationDB SQL Layer link

- README.md
I believe balderdashy/sails-postgresql is the current version of the adapter, not particlebanana/sails-postgresql. Sorry for any misunderstanding!
> fix PostgreSQL adapter link

- lib/waterline/query/dql/create.js
When automatic createdAt and updatedAt property setting is enabled, while the best would be to set both times to some "transaction time", if it's not available, at least on creation the dates should be always set to the same value. The way it was implemented before, the times could differ by a millisecond (or two).
> Set createdAt and updatedAt to the same value on creation.

- ROADMAP.md
This reorganized the road map. The hope here is that we speak more truthful to Waterline development. Features that do not have an active developer on them should be left in backlog till someone picks up the torch.
> Reorganize Roadmap

- lib/waterline/model/lib/defaultMethods/save.js
- test/integration/model/association.remove.hasMany.js
- test/integration/model/association.remove.manyToMany.js
- test/integration/model/save.js
- test/integration/model/toObject.associations.WithForeighKeyTypeDate.js
- test/unit/model/save.js
- test/unit/query/associations/manyToManyThrough.js
> This is a breaking change and will require us to go ahead and push out a smaller version of `0.11`.
This may be controversial but I think it's the right thing to do. The current behavior of `.save()` is awful as documented in #441 #1091 #1037 #954 and probably more. Right now it populates all the attributes which can easily overflow memory. There is a flag to mitigate some of this but it shouldn't happen in the first place.
Trying to determine what to populate based on what attributes are currently set in the model sounds nasty as well. Removing this attribute makes the API cleaner and more predictable as well as a tad bit faster because it has do at minimum one less query.
I want to continue removing pieces related to model serialization in future releases as well so nested/graph …
> Remove second argument to .save()

- lib/waterline.js
- lib/waterline/core/index.js
- lib/waterline/core/validations.js
- test/unit/core/core.validations.js
Part of the confusion and discussion about migrations has been that the attributes define properties in the physical storage layer. It's not ideal to continue adding adapter specific features to attribute definitions. This adds a reserved property to attribute definitions labeled `meta` that allows anything to be passed down to the adapter's `registerConnection` method.
The goal being that any adapter specific details can be defined and passed through. At the same time it cleans up the arguments being passed to `registerConnection` so that instead of trying to make sense of all the internal Waterline details you simple get a dictionary with the keys being the collection identity and each collection containing the following data:
* `definition` - the normalized table definition that was …
> Meta attribute property

- lib/waterline/adapter/sync/strategies/alter.js
- lib/waterline/query/deferred.js
- lib/waterline/query/finders/basic.js
- lib/waterline/query/finders/operations.js
- lib/waterline/utils/normalize.js
- test/unit/adapter/strategy.alter.schema.js
This PR represents the initial work for projections on both the parent and child criteria. It finally brings official support for `select` and adds a `.select()` method to the deferred object. It also adds support for using `select` inside of criteria in a `populate`. 
One thing to note is that any primary keys and foreign keys used in a join will always be selected. This is unavoidable due to the way we currently build up join queries and combine results in cross-adapter populates.
The first thing that needs to happen is tests in [Waterline Adapter Tests](https://github.com/balderdashy/waterline-adapter-tests) to ensure things won't break across the officially supported adapters. There is a corresponding PR in [Waterline Sequel](https://github.com/balderdashy/waterline-sequel/pull/80) …
> Projections

- lib/waterline/adapter/aggregateQueries.js
- lib/waterline/adapter/compoundQueries.js
- lib/waterline/adapter/dql.js
- lib/waterline/adapter/stream.js
- lib/waterline/query/aggregate.js
- lib/waterline/query/composite.js
- lib/waterline/query/deferred.js
- lib/waterline/query/dql/count.js
- lib/waterline/query/dql/create.js
- lib/waterline/query/dql/destroy.js
- lib/waterline/query/dql/join.js
- lib/waterline/query/dql/update.js
- lib/waterline/query/finders/basic.js
- lib/waterline/query/finders/operations.js
- lib/waterline/query/stream.js
Right now there doesn't exist a way to pass additional metadata for a query down to the adapter. This could be helpful when building custom adapters that need handle things like passing connections around or adding information for multi-tenancy. 
This PR adds that ability in a temporary format. For now you can tack on an additional argument to your queries after the callback or use the `.meta()` key in the deferred object builder to pass any arbitrary data down to an adapter function.
Yes this breaks the common node contract of the callback as the last argument and it's weird. I know this isn't a great longterm solution. If you don't use the extra argument everything will work as expected though. The big plus is it gives us this functionality now without breaking every single one of the …
> [Proposal] Pass additional argument to adapters

- lib/waterline/utils/normalize.js
Allows `id` to work in queries when in schemaless mode.
> fix for #1326

- lib/waterline/adapter/sync/strategies/alter.js
- lib/waterline/core/transformations.js
- test/unit/adapter/strategy.alter.schema.js
- test/unit/adapter/strategy.alter.schemaless.js
- test/unit/core/core.transformations/transformations.serialize.js
This fixes an issue with column names on auto migrations.
Before the methods were using the adapter methods so that the new stuff for projections wouldn't work because the `select` calls wouldn't get normalized to use the column names.
This runs the queries through the normal collection methods.
> [Patch] Transformer fix

- lib/waterline/VERSION.js
- lib/waterline/connections/index.js
This allows adapters to behave differently depending on what version of the API is being used.
> Include the api version in connection properties

- lib/waterline/model/lib/associationMethods/add.js
- lib/waterline/model/lib/associationMethods/remove.js
When a custom column name is used in a many-to-many through the joins for the create weren't being mapped correctly.
See this [Stackoverflow Issue](http://stackoverflow.com/questions/37774857/sailsjs-through-association-how-to-create-association) for more details.
> Fix M-T-M Not Being Mapped

- lib/waterline/query/dql/destroy.js
When a join table is made up of two columns both using the same model's primary key, build up an `OR` clause to check both sides of the join.
> Build up an OR clause for reflexive many to many joins

- accessible/allowed-validations.js
- lib/waterline/utils/system/validation-builder.js
- package.json
`sails-hook-rom` will now handle moving top-level properties like `isEmail` into a `validations` property on an attribute, so Waterline now just has to read that property instead of doing all the merging/checking itself.  Also, `required` isn't handled by anchor anymore so the code related to that has been removed.  And Waterline can just defer to anchor to complain about unknown validation rules.
> [patch] Streamline validations

- lib/waterline/methods/find-or-create.js
**Waterline version**: 0.13.0-3
**Node version**: v7.5.0
**NPM version**: 4.1.2
**Operating system**: macOS 10.12.3 (16D32)
<hr/>
Hello,
I'm trying to use latest version of waterline with SailsJS 1.0.0-22, and found a problem with `Model.findOrCreate()`. It behaves the same as `Model.create()` rather than `Model.find()`, i.e it requires `{fetch: true}` meta to return a created/found object.
Model.findOrCreate({ type: 'dog' }, { name: 'Pretend pet type', type: 'dog' }).then(console.log);
// undefined
Model.findOrCreate({ type: 'dog' }, { name: 'Pretend pet type', type: 'dog' }).meta({fetch: true}).then(console.log);
// { id: 1, name: 'Pretend pet type', type: 'dog' }
> [fixes #1444] Model.findOrCreate() should send back an object without {fetch: true} meta

- .gitignore
- Makefile
- lib/waterline/model/lib/associationMethods/remove.js
- test/integration/model/association.remove.hasMany.js
One to many associations were being removed without checking that the actual related object is the same as the one the user is trying to remove.
The fix adds a condition to the update, so that it makes sure that the value matches.
> [fixes #1429] One to many associations were being removed without checking that the actual related object

- lib/waterline/query/dql/destroy.js
- test/integration/model/destroy.js
- test/unit/query/query.destroy.js
See https://github.com/balderdashy/waterline/issues/1418 for details.
> transform values returned from a destroy query if available

- lib/waterline/utils/query/forge-stage-two-query.js
- lib/waterline/utils/query/private/normalize-new-record.js
- lib/waterline/utils/query/process-all-records.js
Until the Sails1 version, the mongo adapter stored the createdAt/updatedAt values as Date types. So to keep everything working we need to allow the same Date type in the v1 of Sails.
With this PR using the 'ref' type will allow auto generate dates with the Date type:
```javascript
attributes: {
createdAt: { type: 'ref', autoCreatedAt: true },
updatedAt: { type: 'ref', autoUpdatedAt: true },
id: { type: 'string', columnName: '_id' }
}
```
This PR goes with another PR in waterline-schema: https://github.com/balderdashy/waterline-schema/pull/90
Plus, we need to document this behavior that all the previous sails-mongo users will need (if they don't use the migrate: 'alter' option).
> [proposal] Allow Date type in autoCreatedAt/autoUpdatedAt with the 'ref' type

- lib/waterline/utils/query/private/normalize-new-record.js
Fix issue where attribute is required and is a model attribute. It was throwing an error about `Error: Consistency violation: `modelIdentity` must be a non-empty string.  Instead got: undefined` because collection was not existing, as it is a required model attribute.
> [patch] Fix issue where attribute is required and is a model attribute

- lib/waterline/utils/query/process-all-records.js
Currently transform warnings to not state which model is the cause of the warning.
We've just done a 0.x -> 1.x Sails upgrade, and had a lot of nulls in places there shouldn't have been (one of the five transform warnings), but the warning does not state which model caused, just the property, which is insufficient when most models have properties like `createdAt` and `updatedAt`.
> [patch] Transform warnings state which model

- lib/waterline.js
For consistency with expectation that model globals are capitalized (without this, the global is `archive`).
> [patch] Add capitalized `globalId` to default archive model.

- lib/waterline.js
- lib/waterline/methods/add-to-collection.js
- lib/waterline/methods/archive.js
- lib/waterline/methods/avg.js
- lib/waterline/methods/count.js
- lib/waterline/methods/create-each.js
- lib/waterline/methods/create.js
- lib/waterline/methods/destroy.js
- lib/waterline/methods/find-one.js
- lib/waterline/methods/find-or-create.js
- lib/waterline/methods/find.js
- lib/waterline/methods/remove-from-collection.js
- lib/waterline/methods/replace-collection.js
- lib/waterline/methods/stream.js
- lib/waterline/methods/sum.js
- lib/waterline/methods/update.js
- lib/waterline/utils/query/forge-stage-two-query.js
- lib/waterline/utils/query/private/normalize-new-record.js
- lib/waterline/utils/query/private/normalize-value-to-set.js
- lib/waterline/utils/query/process-all-records.js
- lib/waterline/utils/system/transformer-builder.js
- package.json
1. Finish up a few straggling things in this PR
2. Update docs (meta key is already covered, just need to write quite a bit more on this subject, including documenting the new model setting)
3. Have sails-generate set up new apps' `config/models.js` file with a default DEK for use during development, and update the boilerplate `config/env/production.js` file so that it explicitly wipes out that config to prevent people accidentally using the checked-in DEK in a production setting
4. Get this working in Node 4 (see https://github.com/simonratner/node-encrypted-attr/pull/3)
5. Figure out a workable solution for Node 0.10/0.12  (possibly just do a conditional require w/ a kind (but firm) error msg if you try to get fresh and fruity with at-rest encryption while using a "mature" version of …
> [proposal] encryption at rest

- lib/waterline/utils/query/private/normalize-value-to-set.js
- test/unit/collection/validations.js
This PR fixes the issue described here: https://github.com/balderdashy/sails/issues/4360
In essence, custom primary key definitions currently have any validation rules ignored, because they are processed separately from "generic" attributes in the "normalize value" logic.  So for a PK defined like:
```
id: {
type: 'string',
required: true,
validations: {
minLength: 6
}
}
```
you can still do `.create({id: 'abc'})` and it'll pass, even though the `id` field doesn't meet the minimum length requirements.  This PR fixes that by ensuring that validation rules apply to both generic and primary key attributes.
Also fixed some existing validation tests and added new tests for the PK case.
> [PATCH] Fix sails issue 4360 (PKs don't get validation rules applied)

- lib/waterline/methods/archive.js
- lib/waterline/utils/query/help-find.js
Fix bug that was occuring in some cases when using .archive() and .archiveOne() with custom column names; including w/ sails-mongo or sails-disk in the new mongo mode
> Fix .archive() and .archiveOne() when using custom column names

- lib/waterline/methods/update-one.js
- Added the skipEncryption:true to the query.meta of the first
forgeStageTwoQuery call and removed it from the second.
Fixes  balderdashy/sails#6939
> Resolved 'UpdateOne: Validation of encrypted attr'
