balderdashy/waterline

package.json

just update `bluebird` dependencies

update bluebird dependencies to 2.9.x

---

lib/waterline/model/lib/association.js
test/unit/model/association.setters.js

Hi!
To avoid annoying:
```
pets.forEach( function(pet) {
Owner.pets.add(pet);
} );
```
Just do:
```
Owner.pets.add(pets);
```

Support Arrays on .add() and .remove()

---

README.md

Add waterline-orientdb to README

---

README.md

Here's the PR from #871, adding a link to the ArangoDB adapter.

Added link to ArangoDB adapter.

---

README.md

Update OrientDB driver reference

---

lib/waterline/adapter/sync/strategies/alter.js
lib/waterline/adapter/sync/strategies/drop.js

#887: Refuse to run alter/drop migration strategies in production.

---

lib/waterline/query/finders/basic.js

Fix small typo in finder type-check.

---

lib/waterline/error/WLError.js

- resolves #913 
- Includes some other minor cleanup

Refactor WLError, set stack writable

---

lib/waterline/utils/nestedOperations/update.js

Disable parent cache on update nested operations

---

lib/waterline/model/lib/internalMethods/defineAssociations.js
lib/waterline/model/lib/model.js
lib/waterline/query/finders/joins.js

This is @nbiton's PR (Decreased processing time by making queries which involve population more efficient) https://github.com/balderdashy/waterline/pull/829 just without the package.json change.

Cherry picked PR #829 (no conflicts)

---

lib/waterline/query/dql/update.js
test/unit/query/query.update.nested.js

add failing test and try fix for #533 and possibly #644

Fix crash for nested model create within update query

---

.travis.yml
package.json

As discussed in https://github.com/balderdashy/waterline/pull/906#issuecomment-87485053, report code coverage to CodeClimate.
cc: @particlebanana

Report code coverage to codeclimate

---

README.md

And replaces .png badges for .svg.

Adds code coverage badge to README

---

lib/waterline/collection/defaults.js
test/integration/Collection.ddl.js

Reverts balderdashy/waterline#962

Revert "#887: change default migration to 'safe'"

---

README.md

Add associations to README.md

---

lib/waterline/model/lib/defaultMethods/toObject.js
test/support/fixtures/model/context.simple.fixture.js
test/unit/model/toObject.js

this *should* help with the recursion issues and solve #891

modify toObject so that you get a POJO back

---

lib/waterline/model/lib/model.js
lib/waterline/query/integrator/index.js
lib/waterline/query/integrator/populate.js
test/support/fixtures/integrator/populateResults.js

Allows you to populate on nosql databases and not lose values.
Possible fix for #366 but needs some more testing before merging in. Passes all current test but I didn't add any new tests for this case.

Allow the integrator to work on values not in the schema

---

lib/waterline/adapter/sync/strategies/alter.js
test/unit/adapter/strategy.alter.schema.js
test/unit/adapter/strategy.alter.schemaless.js

Fixes #966 and adds a few more simple alter migration tests

Fix schema false migration

---

lib/waterline/query/dql/destroy.js
test/integration/model/association.destroy.manyToMany.js

If I understand #928 correctly then this should give the same result without the need for the transformation.

M m leapset fix

---

lib/waterline/utils/helpers.js

Fixed issue https://github.com/sgress454/sails-hook-autoreload/issues/28

Fix autoreload crash with Many-to-Many & MySQL

---

lib/waterline/core/dictionary.js
test/integration/Collection.multipleAdapters.js

- added multiple adapter tests that clarify the functionality and increase coverage
- refactored dictionary builder to use lodash
- added comments to dictionary builder

Test and Refactor Multiple Adapter logic

---

lib/waterline/error/WLError.js
test/unit/error/WLError.test.js

Fixes #1001.
The PR replaces PR #1045, the only difference being that it includes a failing test proving @shaunc's fix does indeed fix the issue.
@particlebanana, @devinivy, please take  a look.

Prevents infinite recursion in "WLError.stack" setter

---

lib/waterline/core/index.js
lib/waterline/core/transformations.js
test/unit/core/core.schema/schema.object.js

check https://github.com/balderdashy/waterline-schema/issues/22 bug

Fix special attribute names - aka "type" + failling test

---

lib/waterline/model/index.js
lib/waterline/model/lib/defaultMethods/save.js
test/integration/model/save.js

This is the same as https://github.com/balderdashy/waterline/pull/954 but with the function signature changed to have `cb` as the last parameter.
All credit to @nkibler7.

Added ability to specify what to populate on save()

---

lib/waterline.js

related to:
https://github.com/balderdashy/waterline/issues/1073

removed deepClone of config settings

---

test/unit/query/associations/transformedPopulations.js

add unit test for transformed criteria

---

lib/waterline/query/aggregate.js
lib/waterline/query/dql/create.js
test/unit/query/query.create.js

Rebased version of #946 from @Esya
Fixes #754.
Docs in balderdashy/waterline-docs#60.

Esya custom attributes

---

package.json

Resolves #1093 
Updates switchback, fixing some bugs and removing the globally-leaked `inspect` variable.

Update switchback dep

---

lib/waterline/utils/types.js

Reverts balderdashy/waterline#1137

Revert "add geometry type"

---

lib/waterline/query/adapters.js

@devinivy @nethoncho this should fix the teardown connection issue.

Fixes #697

---

lib/waterline/model/lib/associationMethods/add.js
lib/waterline/model/lib/associationMethods/remove.js
test/unit/query/associations/manyToManyThrough.js

This fixes the last test of #1134 where `.add` and `.remove` were returning the incorrect values.
cc @atiertant

Fix test suite from #1134

---

lib/waterline/model/lib/defaultMethods/toObject.js
test/integration/model/toObject.associations.WithForeighKeyTypeDate.js
test/unit/query/associations/manyToManyThrough.js

Resolves Issue #1265.
I'll do and fix anything you tell! Just please - merge this.

Through association id datetime fix

---

lib/waterline/model/lib/defaultMethods/toObject.js
test/integration/model/toObject.associations.WithForeighKeyTypeDate.js

Second try to resolve Issue  #1265.
I've refactored the part like this:
```
...
if (record instanceof Date) {
var item = new Date(record);
_.extend(item.__proto__ , record.__proto__);
this.object[association] = item;
// _.isObject() does not match null, so we're good here.
}
...
```
The question is do we need `_.extend(item.__proto__ , record.__proto__);` or it has no sense here, since no one extends Date with custom methods?
@particlebanana 
I'll fix and rewrite anything you say.
Thanks for your patience and care.
I never committed to such a big and serious enterprise projects, so I feel a little nervous :)

Through association id datetime (try 2).

---

ROADMAP.md

Format to match [Sails Roadmap](https://github.com/balderdashy/sails/blob/master/ROADMAP.md).

Roadmap updates

---

lib/waterline/core/typecast.js
test/unit/core/core.cast/cast.boolean.js

Changed boolean casting method to not cast incorrect values

---

Makefile

fixes from #1113

---

lib/waterline/query/dql/destroy.js

Move down to after the deferred return

fix for when destroy is called with invalid arguments using exec

---

lib/waterline/query/finders/dynamicFinders.js

fix issue with dynamic finder names

---

lib/waterline/adapter/sync/strategies/alter.js
lib/waterline/core/transformations.js
package.json
test/unit/adapter/strategy.alter.schema.js
test/unit/adapter/strategy.alter.schemaless.js
test/unit/core/core.transformations/transformations.serialize.js

Brings in the changes from #1341 to back port to the `0.11.x` series.

[patch] Back port changes to 0.11.x branch

---

lib/waterline/model/lib/associationMethods/add.js

Fixes https://github.com/balderdashy/sails/issues/3784

Don't error out if the join record already exists

---

lib/waterline.js
test/alter-migrations/strategy.alter.buffers.js
test/alter-migrations/strategy.alter.schema.js
test/alter-migrations/strategy.alter.schemaless.js

PRs to sails-postgresql and sails-waterline to follow

[patch] Change `registerConnection` to `registerDatastore`

---

lib/waterline/methods/create-each.js
lib/waterline/methods/create.js
lib/waterline/methods/destroy.js
lib/waterline/methods/find-one.js
lib/waterline/methods/find-or-create.js
lib/waterline/methods/update.js
lib/waterline/utils/query/deferred.js
test/unit/callbacks/afterDestroy.destroy.js

Methods cleanup

---

lib/waterline.js

Companion to https://github.com/balderdashy/waterline-schema/pull/63

[patch] Send model defaults to wl-schema

---

ARCHITECTURE.md

Some changes so that samples match up. Added comments prefixed by $$$, please review, and update accordingly or let me know.

[patch] Some changes so that samples match up

---

lib/waterline/model/lib/associationMethods/add.js
lib/waterline/model/lib/associationMethods/remove.js

Update method by which cacheKey for many-to-many-through queries is derived

[fixes #3946] Fix issue 3946

---

lib/waterline/utils/nestedOperations/update.js

Part of https://github.com/balderdashy/waterline/issues/1453

use correct key for through table

---

lib/waterline/utils/query/help-find.js
lib/waterline/utils/query/private/normalize-sort-clause.js

[patch] Default sort to empty array instead of "sort by primary key"

---

lib/waterline/methods/create-each.js
test/unit/callbacks/afterCreate.createEach.js
test/unit/callbacks/beforeCreate.createEach.js

refs https://github.com/balderdashy/sails/issues/4175

[patch] Add `beforeCreate` and `afterCreate` support to `createEach` method.

---

lib/waterline/collection.js

This commit removes an conditional branch that can never be triggered, because the same condition is checked few lines before, and throws an exception.

[patch] Remove dead code

---

CHANGELOG.md

Removed repeated version comment for 0.11.4

[patch] Removed repeated version comment for 0.11.4

---

lib/waterline/utils/query/private/normalize-value-to-set.js
test/unit/collection/validations.js

Fixes typo and swapped unit test description misplaced in fix #1554 to issue #4360

[PATCH] Fixes typo and swapped unit test description misplaced in fix #1554 to issue #4360

---

lib/waterline/methods/find-one.js

Include model name in findOne error message
